server:
  port: 8082

spring:
  application:
    name: pegasus-messenger

  datasource:
    url: jdbc:postgresql://localhost:5432/pegasus-messenger
    username: pegasus
    password: pegasus

  jpa:
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        format-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8081/auth/realms/pegasus/protocol/openid-connect/token/introspect
          client-id: pegasus-messenger-server
          client-secret: oTRYUVig2SdBqhuvEbci6T8aBNmKx7Oh

  cloud.stream:
    function:
      definition: userProfileProcessor
    bindings:
      userProfileProcessor-in-0:
        destination: UPDATE_PROFILE
    kafka:
      streams:
        binder:
          brokers:
            - localhost:29092


logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
      pegasus:
        messenger:
          server: DEBUG

web:
  allowed-origin: http://localhost:4200
