server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pegasus-messenger
    username: pegasus
    password: pegasus

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml