version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: pegasus-messenger
      POSTGRES_USER: pegasus
      POSTGRES_PASSWORD: pegasus
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./create_keycloak_db.sh:/docker-entrypoint-initdb.d/create_keycloak_db.sh

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: pegasus
      DB_PASSWORD: pegasus
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KAFKA_BOOTSTRAP: kafka:9092
    volumes:
      - ./keycloak-spi-kafka.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-spi-kafka.jar
    restart: unless-stopped
    ports:
      - "8081:8080"

    depends_on:
      - db
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
